# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Historia de la teoría de la difracción
author: Dr.Rer.Nat Roman Castañeda and Dr. Edgar Rueda
copyright: '2023'
logo: Caratula.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
  latex_engine: pdflatex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

# Information about where the book exists on the web
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer:
    <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Historia de la teoría de la difracción</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.


launch_buttons:
  notebook_interface: "classic"
  colab_url: ""
  thebe: true

# Idioma del libro, estilo de las referencias
sphinx:
  config:
    language: es
    bibtex_reference_style: author_year
    latex_toplevel_sectioning: 'part'
